theme: jekyll-theme-cayman
title: "Beyond Chat:  Visual Languages for Embodied Human-LLM Interaction in Sensemaking"
description: An IEEE VL/HCC 2025 workshop

# Add remote theme support
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
